Revert "tests/xe: Add system_allocator test"
This reverts commit 41ee4d698fd87085494ceeec1985a2b99222c5b0.

Fix compilation failure on our containers:
../tests/intel/xe_exec_system_allocator.c: In function test_exec:
../tests/intel/xe_exec_system_allocator.c:1210:21: error: MREMAP_DONTUNMAP undeclared (first use in this function); did you mean DONTUNMAP?
      remap_flags |= MREMAP_DONTUNMAP;

Cc: Matthew Brost <matthew.brost@intel.com>
Cc: Jonathan Cavitt <jonathan.cavitt@intel.com>
Cc: Francois Dugast <francois.dugast@intel.com>
Signed-off-by: Kamil Konieczny <kamil.konieczny@linux.intel.com>
Reviewed-by: Zbigniew Kempczyński <zbigniew.kempczynski@intel.com>